### ISSUE TITLE
Bot is not working

### ISSUE THREAD

**Issue by mairabermeo** [colorstackatuw/ColorStack-Discord-Bot#30]
Hello,

I clicked on the invite link and I got the notification that the bot had entered the server but it never made a channel or introduced itself.

**Comment by DavidSalazar123** [comment]
Hello,

Thanks for informing me about this issue. The bot should be back up and running. I suspect that this is happening because with Oracle Cloud Free Tier, if nothing is being read/written to the database it just shuts itself down after 3 days. Will create a separate issue for someone to create health checks to it to prevent it from shutting down

**Comment by DavidSalazar123** [comment]
https://github.com/colorstackatuw/ColorStack-Discord-Bot/issues/29
